name: Publish bottles

on:
  pull_request_target:
    types:
      - labeled

jobs:
  publish:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    env:
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure git
        uses: Homebrew/actions/git-user-config@master

      - name: Checkout PR branch in tap
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr checkout "${{ github.event.pull_request.number }}"

      - name: Pull and publish bottles
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          brew pr-pull \
            --debug \
            --no-cherry-pick \
            --workflows=tests.yml \
            --tap="${{ github.repository }}" \
            "${{ github.event.pull_request.number }}"

      - name: Push bottle commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Merge PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" \
            --merge \
            --delete-branch \
            --repo "${{ github.repository }}"
